### PR TITLE
script

### PR DESCRIPTION
**Pull request by richmondy2000**
This is the current user test script we have. We will add further user tests once we add more functionality to the app.

### CODE REVIEW

**Review by sebems — COMMENTED** [review]
Could you put it in a .md file, I'm not sure it's wise to put docx files on Github

**Review by VelSharon — COMMENTED** [review]
[script.md](https://github.com/calvin-cs262-fall2021-teamF/toothflex-client/files/7571354/script.md)

**Comment by sebems** [comment]
Could you make the tasks to complete bullet points. Because I feel it would be too easy to get lost

**Review by sebems — APPROVED** [review]
Just added on top of the layout you had, Nice work.

**Pull request merged**
